export const quizData = [
  // Cadre institutionnel & réglementaire
  { category: "Institutionnel", question: "Qui est l'employeur de l'ATSEM ?", options: ["Le directeur de l'école", "Le maire de la commune", "L'inspecteur de l'Éducation Nationale", "Le préfet du département"], correct: 1, explanation: "L'ATSEM est un agent territorial. Son employeur est <strong>le maire de la commune</strong>.<br/><br/>Le directeur d'école organise le travail de l'ATSEM pendant le temps scolaire, mais c'est la commune qui recrute, rémunère et gère la carrière de l'ATSEM." },
  { category: "Institutionnel", question: "L'ATSEM est un fonctionnaire de catégorie :", options: ["Catégorie A", "Catégorie B", "Catégorie C", "Catégorie D"], correct: 2, explanation: "L'ATSEM est un fonctionnaire territorial de <strong>catégorie C</strong>.<br/><br/>Les catégories de la fonction publique : A (cadres), B (intermédiaires), C (exécution). L'ATSEM relève de la filière médico-sociale, cadre d'emplois des ATSEM." },
  { category: "Institutionnel", question: "Pendant le temps scolaire, l'ATSEM est placé sous l'autorité fonctionnelle :", options: ["Du maire", "Du directeur de l'école", "De l'enseignant de la classe", "Du responsable des affaires scolaires"], correct: 1, explanation: "Pendant le temps scolaire, l'ATSEM est sous l'autorité fonctionnelle du <strong>directeur de l'école</strong>.<br/><br/>Attention : l'autorité hiérarchique reste le maire (employeur). Le directeur organise le service, l'enseignant précise les tâches au quotidien." },
  { category: "Institutionnel", question: "L'école maternelle accueille les enfants de :", options: ["2 à 5 ans", "3 à 6 ans", "2 à 6 ans", "3 à 5 ans"], correct: 2, explanation: "L'école maternelle accueille les enfants de <strong>2 à 6 ans</strong>.<br/><br/>L'instruction est obligatoire dès 3 ans. Les enfants de 2 ans peuvent être accueillis en TPS (Toute Petite Section) selon les places disponibles." },

  // Hygiène, entretien & sécurité
  { category: "Hygiène", question: "Le bionettoyage consiste à :", options: ["Nettoyer uniquement avec de l'eau", "Nettoyer puis désinfecter", "Désinfecter uniquement", "Balayer à sec"], correct: 1, explanation: "Le <strong>bionettoyage</strong> est un procédé en 2 étapes :<br/>1. <strong>Nettoyage</strong> avec un détergent (enlève les salissures)<br/>2. <strong>Désinfection</strong> avec un désinfectant (élimine les micro-organismes)<br/><br/>Certains produits combinent les deux (détergent-désinfectant)." },
  { category: "Hygiène", question: "Le pictogramme représentant une flamme sur un produit d'entretien signifie :", options: ["Produit corrosif", "Produit inflammable", "Produit comburant", "Produit irritant"], correct: 1, explanation: "Le pictogramme <strong>flamme</strong> signifie que le produit est <strong>inflammable</strong>.<br/><br/>Les principaux pictogrammes : flamme (inflammable), tête de mort (toxique), point d'exclamation (irritant), corrosion (corrosif), environnement (polluant)." },
  { category: "Hygiène", question: "Lors du lavage des mains, la durée minimale recommandée est de :", options: ["10 secondes", "20 secondes", "30 secondes", "1 minute"], correct: 2, explanation: "Le lavage des mains doit durer au minimum <strong>30 secondes</strong>.<br/><br/>Les étapes : mouiller, savonner (paumes, dos, entre les doigts, ongles, poignets), rincer abondamment, sécher avec un essuie-mains à usage unique." },
  { category: "Hygiène", question: "Le protocole HACCP concerne :", options: ["Le nettoyage des locaux", "La sécurité incendie", "La sécurité alimentaire", "La gestion des déchets"], correct: 2, explanation: "<strong>HACCP</strong> (Hazard Analysis Critical Control Point) est un système de maîtrise de la <strong>sécurité alimentaire</strong>.<br/><br/>À l'école, il s'applique à la restauration scolaire : respect de la chaîne du froid, traçabilité des repas, échantillons témoins conservés 5 jours." },

  // Santé & premiers secours
  { category: "Santé", question: "Un enfant saigne du nez (épistaxis). Le bon geste est de :", options: ["Lui pencher la tête en arrière", "Le coucher sur le dos", "Lui pencher la tête en avant et comprimer la narine", "Appliquer de la glace sur le front"], correct: 2, explanation: "En cas d'<strong>épistaxis</strong>, il faut :<br/>1. Asseoir l'enfant<br/>2. <strong>Pencher la tête en avant</strong> (pas en arrière !)<br/>3. Comprimer la narine qui saigne pendant 10 minutes<br/><br/>Si le saignement ne s'arrête pas, appeler le 15." },
  { category: "Santé", question: "Le PAI (Projet d'Accueil Individualisé) est rédigé pour :", options: ["Tous les enfants de l'école", "Les enfants en situation de handicap uniquement", "Les enfants ayant un problème de santé (allergie, diabète...)", "Les enfants en difficulté scolaire"], correct: 2, explanation: "Le <strong>PAI</strong> concerne les enfants atteints de troubles de santé chroniques : <strong>allergies alimentaires, asthme, diabète, épilepsie</strong>...<br/><br/>Il est rédigé par le médecin scolaire et précise les conduites à tenir en cas de crise, les médicaments autorisés et le régime alimentaire." },
  { category: "Santé", question: "En cas de fièvre chez un enfant à l'école, l'ATSEM doit :", options: ["Donner du paracétamol", "Prévenir l'enseignant et les parents", "Appeler directement le SAMU", "Mettre l'enfant sous une douche froide"], correct: 1, explanation: "L'ATSEM <strong>ne peut pas administrer de médicament</strong> sans PAI.<br/><br/>La bonne conduite : <strong>prévenir l'enseignant</strong>, qui contacte les parents. En attendant : découvrir l'enfant, le mettre au calme, lui proposer de boire. Si la fièvre est très élevée (>39°C) et que les parents ne sont pas joignables, appeler le 15." },

  // Développement de l'enfant & pédagogie
  { category: "Pédagogie", question: "En maternelle, le programme est organisé en :", options: ["3 domaines d'apprentissage", "5 domaines d'apprentissage", "7 domaines d'apprentissage", "4 domaines d'apprentissage"], correct: 1, explanation: "Le programme de maternelle comprend <strong>5 domaines</strong> :<br/>1. Mobiliser le langage dans toutes ses dimensions<br/>2. Agir, s'exprimer, comprendre à travers l'activité physique<br/>3. Agir, s'exprimer, comprendre à travers les activités artistiques<br/>4. Acquérir les premiers outils mathématiques<br/>5. Explorer le monde" },
  { category: "Pédagogie", question: "La durée de la sieste en Petite Section est généralement de :", options: ["30 minutes à 1 heure", "1 heure à 1h30", "1h30 à 2 heures", "2 heures à 3 heures"], correct: 2, explanation: "La sieste en PS dure en moyenne <strong>1h30 à 2 heures</strong>.<br/><br/>L'ATSEM veille au bon déroulement : préparer les lits, accompagner l'endormissement, surveiller les enfants, respecter le rythme de chacun. Un enfant qui ne dort pas peut se lever après un temps de repos calme." },
  { category: "Pédagogie", question: "L'ATSEM peut-elle diriger un atelier pédagogique seule ?", options: ["Oui, c'est son rôle principal", "Oui, mais uniquement sous la responsabilité de l'enseignant", "Non, elle n'a pas le droit", "Oui, si elle a le BAFA"], correct: 1, explanation: "L'ATSEM peut encadrer un atelier <strong>sous la responsabilité de l'enseignant</strong>.<br/><br/>C'est l'enseignant qui définit l'objectif, le contenu et les consignes. L'ATSEM met en œuvre l'activité et accompagne les enfants. Elle ne se substitue jamais à l'enseignant dans le rôle pédagogique." },

  // Relations professionnelles
  { category: "Relations pro", question: "Un parent se plaint du comportement de l'enseignant auprès de l'ATSEM. Que doit-elle faire ?", options: ["Donner son avis sur la situation", "Écouter et orienter le parent vers le directeur", "Ignorer la plainte", "En parler aux autres parents"], correct: 1, explanation: "L'ATSEM doit <strong>écouter avec bienveillance</strong> puis <strong>orienter le parent vers le directeur</strong> de l'école.<br/><br/>L'ATSEM est tenue au <strong>devoir de réserve</strong> : elle ne donne pas son opinion sur l'enseignant et ne prend pas parti. La discrétion professionnelle est une obligation du fonctionnaire." },
  { category: "Relations pro", question: "L'obligation de discrétion professionnelle de l'ATSEM signifie :", options: ["Ne jamais parler aux parents", "Ne pas divulguer d'informations sur les enfants ou l'école en dehors du cadre professionnel", "Ne pas communiquer avec les collègues", "Ne pas parler pendant le temps scolaire"], correct: 1, explanation: "La <strong>discrétion professionnelle</strong> est une obligation de tout fonctionnaire.<br/><br/>Cela signifie ne pas divulguer d'informations sur les enfants, les familles ou le fonctionnement interne de l'école en dehors du cadre professionnel. Cela n'empêche pas de communiquer avec les parents dans le cadre de ses missions." },

  // Calculs pratiques
  { category: "Calculs", question: "Un produit d'entretien se dilue à 2%. Quelle quantité de produit faut-il pour préparer 5 litres de solution ?", options: ["10 ml", "50 ml", "100 ml", "200 ml"], correct: 2, explanation: "Dilution à 2% signifie 2 ml de produit pour 100 ml de solution.<br/><br/>Pour 5 litres (= 5000 ml) :<br/>(2 × 5000) / 100 = <strong>100 ml de produit</strong><br/><br/>On complète avec de l'eau pour obtenir 5 litres." },
  { category: "Calculs", question: "Une salle de classe mesure 8 m × 6 m. Quelle est sa surface ?", options: ["14 m²", "28 m²", "42 m²", "48 m²"], correct: 3, explanation: "Surface = longueur × largeur<br/><br/>Surface = 8 × 6 = <strong>48 m²</strong><br/><br/>Ce calcul est fréquent au concours pour déterminer les quantités de produit d'entretien nécessaires." },
]

export function getDayIndex() {
  return Math.floor((Date.now() + 2 * 60 * 60 * 1000) / (1000 * 60 * 60 * 24)) % quizData.length
}

export function getReorderedQuiz() {
  const dayIndex = getDayIndex()
  return [...quizData.slice(dayIndex), ...quizData.slice(0, dayIndex)]
}
