export const quizData = [
  { category: "Calcul de dose", question: "Vous devez préparer 1,5g de Clamoxyl. Vous disposez de flacons de 500mg à diluer dans 5ml. Combien de ml prélevez-vous ?", options: ["5 ml", "10 ml", "15 ml", "20 ml"], correct: 2, explanation: "Conversion : 1,5 g = 1500 mg<br/><br/>Si 500 mg → 5 ml<br/>Alors 1500 mg → <strong>x</strong> ml<br/><br/>Calcul : <strong>(1500 × 5) / 500 = 15 ml</strong><br/><br/><em>Astuce : 1500 est le triple de 500, donc 3 × 5 ml = 15 ml</em>" },
  { category: "Calcul de dose", question: "Vous devez passer 1 litre de soluté physiologique en 8 heures. Quel est le débit en gouttes/minute ? (1 ml = 20 gouttes)", options: ["35 gouttes/min", "42 gouttes/min", "50 gouttes/min", "60 gouttes/min"], correct: 1, explanation: "Volume : 1 L = 1000 ml<br/>En gouttes : 1000 × 20 = 20 000 gouttes<br/>Temps : 8h × 60 = 480 minutes<br/><br/>Débit = Volume / Temps<br/>Débit = <strong>20 000 / 480 ≈ 41,66</strong><br/><br/><em>On arrondit par excès à 42 gouttes/min.</em>" },
  { category: "Produit en croix", question: "Pour réaliser un pansement complexe, 3 infirmières mettent 45 minutes. Combien de temps mettrait 1 seule infirmière travaillant au même rythme ?", options: ["15 minutes", "90 minutes", "135 minutes", "105 minutes"], correct: 2, explanation: "<strong>Proportionnalité inverse</strong> : moins il y a d'infirmières, plus c'est long.<br/><br/>Si 3 infirmières mettent 45 minutes, 1 seule infirmière mettra 3 fois plus de temps.<br/><br/>Calcul : <strong>45 × 3 = 135 minutes</strong>." },
  { category: "Calcul de dose", question: "Un enfant de 12 kg doit recevoir un sirop antipyrétique à la posologie de 15 mg/kg/jour réparti en 3 prises. Le sirop est dosé à 10 mg/ml. Combien de ml par prise ?", options: ["2 ml", "4 ml", "6 ml", "8 ml"], correct: 2, explanation: "Dose totale/jour : 12 kg × 15 mg = 180 mg<br/>Dose par prise (3 prises) : 180 / 3 = <strong>60 mg</strong><br/><br/>Concentration : 10 mg → 1 ml<br/>Donc pour obtenir 60 mg : <strong>60 / 10 = 6 ml</strong>." },
  { category: "Pourcentage", question: "Le poids d'un patient est passé de 80 kg à 72 kg suite à un traitement diurétique. Quel est le pourcentage de perte de poids ?", options: ["8%", "10%", "12%", "15%"], correct: 1, explanation: "Perte de poids : 80 - 72 = <strong>8 kg</strong><br/><br/>Formule : (Perte / Poids initial) × 100<br/>Calcul : <strong>(8 / 80) × 100 = 10%</strong>" },
  { category: "Pourcentage", question: "Vous disposez d'un flacon de 500 ml de Glucosé à 5% (G5). Combien de grammes de glucose contient ce flacon ?", options: ["5 g", "25 g", "50 g", "2,5 g"], correct: 1, explanation: "G5 signifie : 5 g de glucose pour 100 ml.<br/><br/>Pour 500 ml (qui est 5 fois plus grand que 100 ml) :<br/>Calcul : <strong>5 g × 5 = 25 g</strong>." },
  { category: "Pourcentage", question: "Un service hospitalier compte 50 lits. Aujourd'hui, 42 lits sont occupés. Quel est le taux d'occupation du service ?", options: ["84%", "78%", "88%", "82%"], correct: 0, explanation: "Formule : (Lits occupés / Total lits) × 100<br/>Calcul : (42 / 50) × 100<br/><br/>Astuce : multiplier par 2 en haut et en bas pour ramener à 100 :<br/><strong>(42 × 2) / 100 = 84 / 100 = 84%</strong>." },
  { category: "Calcul mental", question: "Diviser une dose médicamenteuse par 0,25 revient à la :", options: ["Multiplier par 4", "Diviser par 4", "Multiplier par 2,5", "Soustraire de 25%"], correct: 0, explanation: "0,25 correspond à la fraction <strong>1/4</strong>.<br/><br/>Règle : diviser par une fraction revient à multiplier par son inverse.<br/>L'inverse de 1/4 est 4.<br/><br/>Donc diviser par 0,25 = <strong>Multiplier par 4</strong>." },
  { category: "Calcul mental", question: "Calculez de tête : 1,5 x 0,6", options: ["0,09", "0,9", "9", "0,96"], correct: 1, explanation: "Astuce de calcul mental :<br/>1) On calcule sans les virgules : 15 × 6 = 90<br/>2) On compte les chiffres après la virgule : 1 pour 1,5 et 1 pour 0,6 (soit 2 au total).<br/><br/>3) On décale la virgule de 2 rangs vers la gauche : <strong>0,90 (soit 0,9)</strong>." },
  { category: "Calcul mental", question: "L'équipe de nuit utilise 0,8 litre de solution désinfectante par chambre. Combien de litres pour 15 chambres ?", options: ["10 litres", "12 litres", "14 litres", "15 litres"], correct: 1, explanation: "Calcul : 15 × 0,8<br/><br/>Astuce :<br/>15 × 1 = 15<br/>On soustrait 15 × 0,2 (qui fait 3)<br/><strong>15 - 3 = 12 litres</strong>." },
  { category: "Équation", question: "Résoudre l'équation suivante pour trouver la valeur de x : 5x - 7 = 18", options: ["x = 3", "x = 4", "x = 5", "x = 6"], correct: 2, explanation: "1) Isoler x :<br/>5x = 18 + 7<br/>5x = 25<br/><br/>2) Diviser par 5 :<br/>x = 25 / 5<br/><strong>x = 5</strong>" },
  { category: "Équation", question: "Résoudre : 3(x + 2) = 21", options: ["x = 5", "x = 7", "x = 9", "x = 15"], correct: 0, explanation: "1) Diviser par 3 des deux côtés :<br/>x + 2 = 21 / 3<br/>x + 2 = 7<br/><br/>2) Soustraire 2 :<br/>x = 7 - 2<br/><strong>x = 5</strong>" },
  { category: "Calcul de dose", question: "Prescription : Héparine 500 UI/h en seringue électrique. Flacon de 25 000 UI dans 50 ml de NaCl. Quel débit en ml/h ?", options: ["0,5 ml/h", "1 ml/h", "2 ml/h", "5 ml/h"], correct: 1, explanation: "Concentration : 25 000 UI dans 50 ml<br/>Soit 25 000 / 50 = <strong>500 UI par ml</strong>.<br/><br/>Pour 500 UI/h, il faut <strong>1 ml/h</strong>." },
  { category: "Conversion", question: "Convertir 0,075 g en milligrammes.", options: ["0,75 mg", "7,5 mg", "75 mg", "750 mg"], correct: 2, explanation: "1 g = 1000 mg<br/><br/>0,075 g × 1000 = <strong>75 mg</strong>.<br/><br/><em>Astuce : déplacer la virgule de 3 rangs vers la droite.</em>" },
  { category: "Calcul de dose", question: "Prescription de Doliprane 1g toutes les 6h. Quelle est la dose quotidienne totale ?", options: ["2 g", "3 g", "4 g", "6 g"], correct: 2, explanation: "24h / 6h = 4 prises par jour.<br/><br/>Dose totale : 4 × 1 g = <strong>4 g/jour</strong>.<br/><br/><em>Attention : la dose max de paracétamol est de 4g/jour chez l'adulte.</em>" },
  { category: "Pourcentage", question: "Un flacon de Bétadine contient 10% de povidone iodée. Combien de grammes dans un flacon de 250 ml ?", options: ["10 g", "25 g", "50 g", "100 g"], correct: 1, explanation: "10% signifie 10 g pour 100 ml.<br/><br/>Pour 250 ml : (10 × 250) / 100 = <strong>25 g</strong>." },
  { category: "Calcul de dose", question: "Un nourrisson de 8 kg doit recevoir du Nurofen à 10 mg/kg/prise. Le sirop est dosé à 20 mg/ml. Combien de ml par prise ?", options: ["2 ml", "4 ml", "6 ml", "8 ml"], correct: 1, explanation: "Dose par prise : 8 kg × 10 mg = 80 mg<br/><br/>Concentration : 20 mg → 1 ml<br/>Pour 80 mg : 80 / 20 = <strong>4 ml</strong>." },
  { category: "Produit en croix", question: "Si 250 ml de perfusion passent en 2h, combien de ml passent en 30 minutes ?", options: ["31,25 ml", "62,5 ml", "75 ml", "125 ml"], correct: 1, explanation: "2h = 120 minutes<br/><br/>Si 250 ml → 120 min<br/>Alors x ml → 30 min<br/><br/>x = (250 × 30) / 120 = 7500 / 120 = <strong>62,5 ml</strong>." },
  { category: "Conversion", question: "Convertir 2500 µg en milligrammes.", options: ["0,25 mg", "2,5 mg", "25 mg", "250 mg"], correct: 1, explanation: "1 mg = 1000 µg<br/><br/>2500 µg / 1000 = <strong>2,5 mg</strong>." },
  { category: "Calcul de dose", question: "Prescription : Morphine 0,1 mg/kg en IV pour un patient de 70 kg. Ampoule de 10 mg/ml. Combien de ml injectez-vous ?", options: ["0,7 ml", "1 ml", "3,5 ml", "7 ml"], correct: 0, explanation: "Dose : 0,1 × 70 = 7 mg<br/><br/>Ampoule : 10 mg dans 1 ml<br/>Pour 7 mg : 7 / 10 = <strong>0,7 ml</strong>." }
]

export function getDayIndex() {
  return Math.floor((Date.now() + 2 * 60 * 60 * 1000) / (1000 * 60 * 60 * 24)) % quizData.length
}

export function getReorderedQuiz() {
  const dayIndex = getDayIndex()
  return [...quizData.slice(dayIndex), ...quizData.slice(0, dayIndex)]
}
